services:
  # Backend Node.js server for development
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: confluence-backend-dev
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
    networks:
      - confluence-network

  # Frontend React app for development
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: confluence-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:3002
    volumes:
      # Mount source code for hot reloading
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - confluence-network
    stdin_open: true
    tty: true

networks:
  confluence-network:
    driver: bridge