services:
  # Backend Node.js server
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: confluence-backend
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
    networks:
      - confluence-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3002/api/health', (res) => process.exit(res.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend React app with serve
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.simple
    container_name: confluence-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - confluence-network
    environment:
      - REACT_APP_API_URL=http://localhost:3002

networks:
  confluence-network:
    driver: bridge

volumes:
  # Add any persistent volumes if needed
  node_modules_cache: